[versions]
micronaut = "5.0.0-M20"
micronaut-gradle-plugin = "4.6.2"

jaxb-api = "2.3.1"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]

