[versions]
micronaut = "4.0.0-M2"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.0-M1"

groovy = "4.0.11"
spock = "2.3-groovy-4.0"
jaxb-api = "2.3.1"
kotlin = "1.8.21"

[libraries]

jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

