[versions]
micronaut = "5.2.0"
micronaut-gradle-plugin = "5.0.2"

jaxb-api = "2.3.1"

[libraries]
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]

